name: Periodic Commit

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  commit:
    name: Commit Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update README.md
        run: |
          date=$(date +'%Y-%m-%d %H:%M:%S')
          echo "Last updated: $date" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Automated commit every 5 minutes" || echo "No changes to commit"
          git push origin main
