name: Scheduled Commit

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/1 * * * *'

jobs:
  commit:
    name: Commit Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Make changes
        run: |
          # Create a dummy file or modify existing files
          echo "Commit made at $(date)" > commit.txt

      - name: Commit and push changes
        run: |
          git add commit.txt
          git commit -m "Automated commit at $(date)"
          git push

