name: Update README

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "New content as of $(date)" >> README.md

      - name: Commit and push
        run: |
          git config --global user.email "ramnarayanan938474@gmail.com"
          git config --global user.name "ravi"
          git add README.md
          git commit -m "Update README"
          git push origin main
