name: Periodic Commit

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update README.md
        run: |
          date=$(date +'%Y-%m-%d %H:%M:%S')
          echo "Last updated: $date" > README.md
      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated commit every 5 minutes"
          git push origin main
